Repository ZupIT/ritchie-formulas-demo, pull requests merged in 2020-10, with the labels that each got.

#13 [FORMULA] rit game roll dice
  game/help.json
  game/roll/dice/Dockerfile
  game/roll/dice/Makefile
  game/roll/dice/README.md
  game/roll/dice/build.bat
  game/roll/dice/config.json
  game/roll/dice/docs/img/rit-game-roll-dice.png
  game/roll/dice/help.json
  game/roll/dice/metadata.json
  game/roll/dice/set_umask.sh
  game/roll/dice/src/formula/formula.py
  game/roll/dice/src/main.py
  game/roll/dice/src/requirements.txt
  game/roll/help.json
Labels: Hacktoberfest

#19 Add tutorial field in config.json files
  demo/coffee-go/config.json
  demo/coffee-java/config.json
  demo/coffee-node/config.json
  demo/coffee-python/config.json
  demo/coffee-shell/config.json
  demo/hello-world/config.json
Labels: Hacktoberfest

#21 [FORMULA] rit game play snake
  game/play/help.json
  game/play/snake/Dockerfile
  game/play/snake/Makefile
  game/play/snake/README.md
  game/play/snake/build.bat
  game/play/snake/config.json
  game/play/snake/docs/snake-game.gif
  game/play/snake/help.json
  game/play/snake/metadata.json
  game/play/snake/set_umask.sh
  game/play/snake/src/main.ps1
Labels: Hacktoberfest

#23 Update README.md to RIT DEMO COFFEE-PYTHON formula
  demo/coffee-python/README.md
Labels: hacktoberfest-accepted

#24 Update README.md file on coffee-java
  demo/coffee-java/README.md
Labels: hacktoberfest-accepted

#26 Update README.MD on coffee-shell
  demo/coffee-shell/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#27 Update README.MD on coffee-node
  demo/coffee-node/README.md
Labels: Hacktoberfest, hacktoberfest-accepted
